### ISSUE TITLE
Formatter introduces trailing whitespace after headings without titles

### ISSUE THREAD

**Issue by kieran-ryan** [cucumber/gherkin-utils#34]
### 👓 What did you see?

The gherkin-utils formatter introduces trailing whitespace after the `Examples:` keyword within Scenario Outlines. This differs from documented usage within the [Gherkin Reference documentation for a Scenario Outline](https://cucumber.io/docs/gherkin/reference/#scenario-outline) and [good test-data samples for examples](https://github.com/cucumber/gherkin-utils/blob/main/testdata/good/example_token_multiple.feature#L6) within the gherkin-utils repository.

```diff
diff --git a/testdata/good/example_token_multiple.feature b/testdata/good/example_token_multiple.feature
index 0471b7f..8d5ba87 100644
--- a/testdata/good/example_token_multiple.feature
+++ b/testdata/good/example_token_multiple.feature
@@ -3,6 +3,6 @@ Feature: Example token used multiple times
   Scenario Outline: Token used twice in a single step
     Given <what> <what>
 
-    Examples:
+    Examples: 
       | what  |
       | usage |
```

### ✅ What did you expect to see?

No trailing whitespace after the `Examples:` keyword within a formatted Scenario Outline.

### 📦 Which tool/library version are you using?

- cucumber/gherkin-utils: v8.0.5
- NodeJS: v18.16.0

### 🔬 How could we reproduce it?

1. Clone the [gherkin-utils](https://github.com/cucumber/gherkin-utils) repository
2. Within the repository, install the [gherkin-utils npm package](https://www.npmjs.com/package/@cucumber/gherkin-utils): `npm i @cucumber/gherkin-utils`
3. Identify a 'good' test data sample feature file that contains an examples keyword without trailing whitespace
4. Run the gherkin-utils formatter against the feature file: `npx @cucumber/gherkin-utils format testdata/good/example_token_multiple.feature`
5. Perform a git diff against the formatted feature file: `git diff testdata/good/example_token_multiple.feature`

It will be observed that trailing whitespace was introduced after the examples keyword.

### 📚 Any additional context?

This is due to a common operation being applied to several keywords, where the keyword text itself `Examples` is suffixed with `: ` - see [pretty.ts](https://github.com/cucumber/gherkin-utils/blob/main/javascript/src/pretty.ts#L96). The examples keyword is not considered separately according to its formatting requirements - doing so would resolve the issue.

**Comment by mpkorstanje** [comment]
Note that like all other headings the examples can have a title. For example `Examples: First group of examples`.

So the solution would probably build on the work done in:
https://github.com/cucumber/gherkin-utils/pull/25/files

**Comment by kieran-ryan** [comment]
Thanks @mpkorstanje! I have expanded the scope to include all headings and have raised a PR to fix the issue.
