### ISSUE TITLE
Formatter does not preserve trailing comments

### ISSUE THREAD

**Issue by xeger** [cucumber/gherkin-utils#38]
### 👓 What did you see?

When the final lines of a block are commented, the formatter removes them from its output.

### ✅ What did you expect to see?

Comments should be preserved.

### 📦 Which tool/library version are you using?

Version 8.0.5 of this package.

### 🔬 How could we reproduce it?

See [this branch](https://github.com/cucumber/gherkin-utils/compare/trailingComments) for a reproduction of the problem in unit tests.

**Comment by jeeeem** [comment]
Awesome, any plan in including this update in vscode extension next release?
