### ISSUE TITLE
Create a static method to pretty print gherkin

### ISSUE THREAD

**Issue by nddipiazza** [cucumber/gherkin-utils#4]
I find myself wishing there was a simple SDK with the ability to pretty print (format) gherkin files.

Like how intellij cucumber plugin formats them is exactly what I want. 

Is there some way to add a simple static method for this? 

`GherkinFormatter.prettyPrint(gherkinString)`

I think there is a way to do this with the library, but it's not as simple.

**Comment by kieran-ryan** [comment]
@mpkorstanje, assume this can be closed? The Java implementation now satisfies the original request, if not mistaken.

https://github.com/cucumber/gherkin-utils/blob/7766139a7e854ecc619dfc5e69448055cafab159/java/src/main/java/io/cucumber/gherkin/utils/pretty/Pretty.java#L8-L28

**Comment by mpkorstanje** [comment]
Seems good enough to me.
