### ISSUE TITLE
Using vulnerable version of source-map-support : 0.5.21

### ISSUE THREAD

**Issue by Scc33** [cucumber/gherkin-utils#93]
Hello,

Looks like this package is using a vulnerable version of source-map-support.

evanw/node-source-map-support#341

Just wanted to point out this new vulnerability.

**Comment by mpkorstanje** [comment]
Thanks for reporting this, but as noted on https://security.snyk.io/vuln/SNYK-JS-SOURCEMAPSUPPORT-6112477

> Directory Traversal The advisory has been revoked - it doesn't affect any version of package [source-map-support](https://security.snyk.io/package/npm/source-map-support)
